---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
      with_items:
        - httpd
        - mod_ssl

    - name: generate certificate 01
      shell: >
        cd /etc/httpd/conf && \
        openssl genrsa -out server.key 2048 && \
        openssl req -new -key server.key -out server.csr \
          -subj '/C=JP/ST=Tokyo/L=Tokyo/O=Example Ltd./OU=Web/CN=example.com' && \
        openssl x509 -in server.csr -days 3650 -req -signkey server.key > server.crt
      args:
        creates: "/etc/httpd/conf/server.crt"

    - name: modify config file 01
      replace:
        dest: /etc/httpd/conf.d/ssl.conf
        regexp: "^SSLCertificateFile.*$"
        replace: "SSLCertificateFile /etc/httpd/conf/server.crt"

    - name: modify config file 02
      replace:
        dest: /etc/httpd/conf.d/ssl.conf
        regexp: "^SSLCertificateKeyFile.*$"
        replace: "SSLCertificateKeyFile /etc/httpd/conf/server.key"

    - name: set index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: start httpd
      service:
        name: httpd
        state: started  
        enabled: yes
